test: remove only flag
eXist-db/node-exist pull request #304
Opened 2023-10-17 16:56 UTC by line-o

2023-10-17 18:34 UTC, duncdrum requested changes
The changes look good in principle, but the last commit doesn’t seem to have the desired effect. 

On ci the tests run against release, but the release step runs against latest.  

I think we sold re factor ci so that there failing exist v7 test runs in a test step, and have a release step that only runs when all test s are Green. That  step doesn’t need to run npm test again imv. 

once the adapted v7 tests pass on v7 good to merge. 

In case of a major version upgrade I would bump node compatibility. V14 is ancient

2023-10-17 20:36 UTC, line-o commented
@duncdrum the failing two tests in the `latest` exist-db is an issue in exist-db itself. I did mark is as experimental as we did in other projects before.

2023-10-17 20:37 UTC, line-o commented
Not testing on 14 is non-breaking as you can still install the package.

2023-10-17 21:10 UTC, line-o commented
related issue https://github.com/eXist-db/exist/issues/5096

2023-10-18 11:17 UTC, duncdrum requested changes
I think you need to still set `continue-on-error` based on `experimental`. See https://github.com/eXist-db/node-exist/actions/runs/6552606348/job/17796640756?pr=304

2023-10-18 11:27 UTC, line-o commented on .github/workflows/semantic-release.yml
> +    continue-on-error: ${{ matrix.experimental }}
@duncdrum it's here

2023-10-18 11:34 UTC, merged