fix(connection): readOptionsFromEnv sets protocol
eXist-db/node-exist pull request #305
Opened 2023-10-18 10:20 UTC by line-o

This is needed to allow REST connections using
`http:` to override the default (`https:`).

2023-10-18 11:12 UTC, duncdrum requested changes
If its necessary it should be mentioned here https://github.com/eXist-db/node-exist#rest . Having both `environmentOptions.secure` and `environmentOptions.protocol` isn't self-evident

2023-10-18 12:23 UTC, line-o commented
@duncdrum I just re-read the section explaining the REST endpoint and agree that it should include a section how to configure that connection - by hand - _and_ also point out that the options returned from `readOptionsFromEnv` can be used there, too.

2023-10-19 21:27 UTC, line-o commented
@duncdrum your demand to better document connection options lead to a serious quality of life improvement :)

2023-10-21 09:14 UTC, duncdrum approved these changes
Nice this looks much better now

2023-10-21 09:15 UTC, merged